### ISSUE TITLE
-purge-tags does not check if delete is enabled

### ISSUE THREAD

**Issue by stefaneg** [Quiq/registry-ui#15]
When running 
```
docker exec -t registry-ui /opt/docker-registry-ui -purge-tags
```
there is no obvious feedback indicating that it did not delete anything if the registry does not have delete enabled. Since delete is disabled by default in docker registries, I would expect some feedback, and preferrably some fail-fast mechanism. This is a big time waster. Running this process takes about 40 minutes on my registry, multiply that by 2 since ppl probably dry-run this first.

Same actually goes for the web UI, there is no indication of the failure in the UI, only that the tag did no disappear.

**Comment by stefaneg** [comment]
Btw, thanks for excellent job otherwise 👍

**Comment by roman-vynar** [comment]
I agree, however I am not sure there is a way to fast-fail with delete as we don't know what to try to delete until process things first. May be I should describe in README that `delete` option to be enabled on registry.

**Comment by roman-vynar** [comment]
https://github.com/Quiq/docker-registry-ui#schedule-a-cron-task-for-purging-tags

**Comment by stefaneg** [comment]
A big improvement to document it.

Two ideas on failing faster:
a. You can stop the batch delete process on the first failed delete with 405 response, which is what DR responds with if I remember correctly.

b. For fastest possible validation, you can push some small image, like alpine, with a UUID tag, and try to delete it again. Probably easiest to implement a specific command line option to do this, "verify-delete-enabled" or something.

**Comment by roman-vynar** [comment]
You are welcome to make a PR with this feature :)
