### ISSUE TITLE
tags not listed when the catalog is deeper than 2 

### ISSUE THREAD

**Issue by RainerW** [Quiq/registry-ui#24]
We use catalogs in the registry as folders.

e.g.  ${company}/${project}/${module} as catalog name.

![image](https://user-images.githubusercontent.com/118649/47918666-83fe7500-dead-11e8-81c0-42ac303cb46a.png)

The ui does actually list the subrepositories when selecting the Namespace ${catalog} and also corretly shows the tag count, but when clicking on that catalog it ends in a empty tag list page. 

![image](https://user-images.githubusercontent.com/118649/47918704-9d9fbc80-dead-11e8-9d4c-4b8a1068d102.png)

The Link does contain the / as %F2 but also when entering the url with a / the ui will just list a "empty repository" which it is not ( http://server:5000/v2/dev-ploy/ploy-jnlp-slave/release/tags/list does list the correct tags, also the namespace overview does list the corret tag count)

http://server:8000/ui/dev-ploy/ploy-jnlp-slave%2Frelease
http://server:8000/ui/dev-ploy/ploy-jnlp-slave/release

**Comment by roman-vynar** [comment]
We have made a full rewrite and now an arbitrary number of repository levels are supported. Even a mix or sub-repos and tags.
