### ISSUE TITLE
404 error for pull-through cache and official images

### ISSUE THREAD

**Issue by maximsnezhkov** [Quiq/registry-ui#26]
Hello.  
While I use local docker registry as pull-through cache, all official images from hub.docker.com ie `https://hub.docker.com/_/mysql` or `https://hub.docker.com/_/python` stored within my local registry with path `library/python` and `library/mysql`.  
When I try to locate them by **docker-registry-ui** I find it in library namespace and docker-registry-ui request them by `my-local-registry:5000/v2/python/tags/list`  
```
2018-12-17 08:50:15 - registry.client - INFO - GET /v2/python/tags/list 404 Not Found
```
instead of `my-local-registry:5000/v2/library/python/tags/list`  
```
 $ curl -XGET -I https://my-local-registry:5000/v2/library/python/tags/list
HTTP/2 200 
server: nginx/1.15.6
date: Mon, 17 Dec 2018 09:07:22 GMT
content-type: application/json; charset=utf-8
vary: Accept-Encoding
docker-distribution-api-version: registry/2.0
x-content-type-options: nosniff
strict-transport-security: max-age=15724800; includeSubDomains
```
At the same time all of my local images stored for example in `my-local-registry:5000/v2/my-python-image/tags/list` and there is no problem for this images.

**Comment by roman-vynar** [comment]
`_` in Docker Hub stands `library` for Docker Registry which is the default namespace.

**Comment by roman-vynar** [comment]
We have made a full rewrite and now an arbitrary number of repository levels are supported. Even a mix or sub-repos and tags. No more namespace concept.
