### ISSUE TITLE
[feature request] provide docker registry metrics

### ISSUE THREAD

**Issue by ntavares** [Quiq/registry-ui#49]
Hi,

We're using docker-registry-ui, and I can't find an exporter when the storage backend is not a filesystem. I just thought that, since docker-registry-ui is already crawling the entire registry, why not provide metrics along as well?

I know it's a bit out of scope from docker-registry-ui, but looks like a very efficient way to provide an exporter.

**Comment by roman-vynar** [comment]
docker-registry-ui is not crawling a storage backend, in our case we are using S3, not a filesystem.  docker-registry-ui is calling Docker Registry HTTP API.

**Comment by ntavares** [comment]
@roman-vynar I know, but you are crawling the entire registry _via_ Docker Registry API, right? That's what I wrote... do you think this is feasible? It'd should be "just about" instrumenting every time you parse a "repository" and/or a tag, hence me hoping that you agree in providing these metrics. 

This can be regarded as metrics from registry-ui itself, like: "number of tags by repositories (parsed by registry-ui)".... I'd submit a PR myself, but I'm not skilled at Go....

**Comment by roman-vynar** [comment]
We have made a full rewrite and you are welcome to make a PR to support prometheus metrics :)
