### ISSUE TITLE
Sorting Images

### ISSUE THREAD

**Issue by RyanLiu6** [Quiq/registry-ui#51]
Currently, I'm only able to sort images by their image names. I would like to be able to sort on other things, mostly just on the age of the image. It would be nice to be able to sort and get the oldest / newest images.

Thanks!

**Comment by roman-vynar** [comment]
There is no way to sort images by creation date/age. Because the registry itself is badly designed and does not provide any efficient way to get this information w/o making extra calls. This is an expensive operation.
