### ISSUE TITLE
Support showing image details for OCI images in the registry

### ISSUE THREAD

**Issue by CJLove** [Quiq/registry-ui#52]
I'm using the current docker-registry-ui image and Docker registry 2.7.

By default podman builds OCI images.  I'm unable to view image details for these images using docker-registry-ui.

To query the manifest from an OCI image in the registry you need to add an Accept header:

```
fir ~  > curl -k -H "Accept:application/vnd.oci.image.manifest.v1+json" https://fir.local:3005/v2/
arm32v7/builder/manifests/latest
{"schemaVersion":2,"config":{"mediaType":"application/vnd.oci.image.config.v1+json","digest":"sha256:2c81c9601fbaed4945e96b93c9d22417f869bba3be1758dd1e51bba1eda42ae0","size":1119},"layers":[{"mediaType":"application/vnd.oci.image.layer.v1.tar+gzip","digest":"sha256:a4108b69c3f2a06c303ddfd007e1a739e368de5a337e7dc3c298ba3e454cfb08","size":2455704},{"mediaType":"application/vnd.oci.image.layer.v1.tar+gzip","digest":"sha256:6e9e5cf384fc0ebb51c5ed1f3374762f8a28cfa5c6ee4e9517b29b89ed0ef6be","size":124872615}]}
```

Workaround is to build the image in docker form:  `podman --format docker`

**Comment by dmaes** [comment]
+1 for support for OCI images. Deleting images also doesn't work without the `Accept:application/vnd.oci.image.manifest.v1+json` header. Currently fixing it by letting my proxy inject that header, but that's a dirty fix.

**Comment by dmaes** [comment]
Building docker-formatted images with podman is taking a step back though.

I'll take a look and maybe make a PR, my go skills have improved a bit since 6mo ago...

**Comment by roman-vynar** [comment]
We have made a full rewrite and OCI is now fully supported.
