### ISSUE TITLE
default namespace

### ISSUE THREAD

**Issue by robertotrevisan** [Quiq/registry-ui#57]
Hi! can I change load default namespace "library" to another custom?

**Comment by roman-vynar** [comment]
Hi, 

It is historically  `library` because it is `library` in the docker API. In theory, it is possible to implement a replacement or make it custom and still map to `library` internally. But it has to be implemented, not a quick fix.

**Comment by roman-vynar** [comment]
We have made a full rewrite and now an arbitrary number of repository levels are supported. Even a mix or sub-repos and tags. No more namespace concept.
