### ISSUE TITLE
Go binary without Docker?

### ISSUE THREAD

**Issue by bodsch** [Quiq/registry-ui#65]
Is it possible to provide a pure go binary?
I would create a suitable Ansible role for this.

**Comment by roman-vynar** [comment]
Sure, see the Dockerfile itself. You can just compile a binary yourself.
You need to supply "static/" and "template/" folder along with the binary.

**Comment by bodsch** [comment]
I was "only" going to roll out a binary, but I'll try my hand at a GitHub workflow and put in a pull request if it's wanted. ;)

**Comment by bodsch** [comment]
I have a draft of an [Ansible role](https://github.com/bodsch/ansible-registry-ui) ready and in my fork of your repository the GitHub workflow was already running.

**Comment by roman-vynar** [comment]
Thanks but I don't think it fits this repo.
