### ISSUE TITLE
Some flexibility for configuration parameters

### ISSUE THREAD

**Issue by mstup** [Quiq/registry-ui#75]
Hi,

Needs some more flexibility in defining the configuration parameters.

For example:
To use in Docker Compose, may I overwrite some hardcoded parameters defined in `config.yml` file by value of environment variable for Docker container?

**Comment by roman-vynar** [comment]
Any specific parameters do you want?

**Comment by mstup** [comment]
And wants to have possibility to switch to use secure or insecure connection with registry host, but not only host:port

**Comment by dginhoux** [comment]
Hi, 

Is there a way to custom catalog items number ?

**Comment by roman-vynar** [comment]
@dginhoux what exactly do you mean?

**Comment by roman-vynar** [comment]
Done https://github.com/Quiq/registry-ui/commit/f7e40bece83307d08aa731805b0ef795d17a223e
Will be released with a new version.
