### ISSUE TITLE
ipv6 addresses are not displayed correctly

### ISSUE THREAD

**Issue by ghislain-bernard** [Quiq/registry-ui#77]
Hi,

First, thanks for all the work into this project.

I noticed that when registry notifications contain ipv6 addresses, the event log displays truncated addresses.

![IP-address-ipv6](https://github.com/user-attachments/assets/9fcaa0b5-6df9-401a-8454-4d868965016c)
Registry UI v0.10.2

Thanks.

**Comment by ghislain-bernard** [comment]
The database field is too small and the field extracted seen not support ipv6.

```go
const (
	userAgent    = "registry-ui"
	schemaSQLite = `
	CREATE TABLE events (
...
		ip VARCHAR(15) NULL,
```

```go
ip := strings.Split(i.Get("request.addr").String(), ":")[0]
```

Perhaps complicated to modify?

I'm a golang novice ;)

**Comment by roman-vynar** [comment]
Thanks!

You can try to alter a field in the database to store a longer value.
```
ALTER TABLE events modify column ip varchar(45) null;
```
More value sanitization will require code changes. Please report back what the full values of IPv6 look like in your case.

**Comment by ghislain-bernard** [comment]
Hi,

Good idea.

But, unfortunately the ipv6 address is cut by the rule on the ':'

The event received :
```json
       "request": {
          "id": "46f6f513-6854-4786-b167-e5e73f2a373d",
          "addr": "[fd1a:c221:8473:3b0e:0:242:ac11:8]:36828",
          "host": "registry.homeware.ovh",
          "method": "PUT",
          "useragent": "docker/27.0.3 go/go1.22.4 git-commit/662f78c0b1 kernel/6.9.9-arch1-1 os/linux arch/amd64 UpstreamClient(Docker-Client/27.0.3 \\(linux\\))"
         }
```

**Comment by roman-vynar** [comment]
True, ok. So the code fix is needed and a db field alternation.

**Comment by roman-vynar** [comment]
Made a code fix which is available with the latest release https://github.com/Quiq/registry-ui/releases/tag/0.10.3
